// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        maven {
            url = 'https://gdartifactory1.jfrog.io/artifactory/gradle-gdcorp-commerce-snapshots-local'
            credentials {
                username = System.getenv('ARTIFACTORY_WRITE_USERNAME') ?: ''
                password = System.getenv('ARTIFACTORY_WRITE_PASSWORD') ?: ''
            }
        }
        maven {
            url = 'https://gdartifactory1.jfrog.io/artifactory/gradle-gdcorp-commerce-releases-local'
            credentials {
                username = System.getenv('ARTIFACTORY_WRITE_USERNAME') ?: ''
                password = System.getenv('ARTIFACTORY_WRITE_PASSWORD') ?: ''
            }
        }
        maven {
            url = 'https://gdartifactory1.jfrog.io/artifactory/java-virt'
            credentials {
                username = System.getenv('ARTIFACTORY_USERNAME') ?: ''
                password = System.getenv('ARTIFACTORY_PASSWORD') ?: ''
            }
        }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.7.0"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven {
            url = 'https://gdartifactory1.jfrog.io/artifactory/gradle-gdcorp-commerce-snapshots-local'
            credentials {
                username = System.getenv('ARTIFACTORY_WRITE_USERNAME') ?: ''
                password = System.getenv('ARTIFACTORY_WRITE_PASSWORD') ?: ''
            }
        }
        maven {
            url = 'https://gdartifactory1.jfrog.io/artifactory/gradle-gdcorp-commerce-releases-local'
            credentials {
                username = System.getenv('ARTIFACTORY_WRITE_USERNAME') ?: ''
                password = System.getenv('ARTIFACTORY_WRITE_PASSWORD') ?: ''
            }
        }
        maven {
            url = 'https://gdartifactory1.jfrog.io/artifactory/java-virt'
            credentials {
                username = System.getenv('ARTIFACTORY_USERNAME') ?: ''
                password = System.getenv('ARTIFACTORY_PASSWORD') ?: ''
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}